### PR TITLE
Tags/3.6 Prepare for 3.x-dev | 3.6.x-dev framework version

### PR DESCRIPTION
**Pull request by Doniz**
Hi, would be great if you merge this request. I prepare to latest framework 3 version. And also updated a composer file. Please take look.

### CODE REVIEW

**Comment by Doniz** [comment]
anybody here? hello ?

**Comment by striky1** [comment]
You don't write changes to changelog :)

**Comment by Doniz** [comment]
ohh, forget about that. I will update later.

**Comment by Doniz** [comment]
by the way @unclecheese could you update composer file? Because there is no package like `silverstripe/langeditor`.

**Comment by unclecheese** [comment]
Done!

**Pull request merged**
